### ISSUE TITLE
Allow usage with autotest gem, by removing ZenTest runtime dependency

### ISSUE THREAD

**Issue by grosser** [carlosbrando/autotest-notification#1]
I wanted to try if autotest-notification would work with the pure autotest gem, but even if i do a gem install autotest-notification + gem uninstall ZenTest + gem install autotest, autotest_notification fails with:

```
>> require 'autotest_notification' 
Gem::LoadError: Could not find RubyGem ZenTest (>= 3.9.2)
from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:827:in `report_activate_error'
from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:261:in `activate'
...
```

can you remove this runtime dependency (e.g. switch to a simpler `require 'autotest'`), so all autotest versions can happily use autotest-notification ?

**Comment by carlosbrando** [comment]
Changed!

Thank you.

Use: sudo gem install autotest-notification
