### ISSUE TITLE
undefined local variable or method `autotest' for AutotestNotification:Module

### ISSUE THREAD

**Issue by ggrocco** [carlosbrando/autotest-notification#14]
Hi Carlos

in the line 30 of lib/autotest_notification.rb has one erro, you are trying to use a variable named 'autotest' but now the name of variable is only 'at'.

Thank you,
Georgeo

**Comment by carlosbrando** [comment]
Can you test it with the github version of the gem? I think it was fixed.

**Comment by ggrocco** [comment]
Hi Carlos,

Something is not working correct on the 2.3.3.

The version o RubyGem still with problem on the same variable. So I use direct on the Github, but some internal error on the Autotest Notification do the Autotest stop to work and don't notify anything. Unfortunately don't show any error only stop the autotest. 

If I stop to use the Autotest Notification (an-uninstall) the autotest back to work... 

I'll try found where is the problem and after I talk to you.

Thank you,
Georgeo

**Comment by carlosbrando** [comment]
Thanks.

**Comment by argent-smith** [comment]
Dear Carlos, are you planning including a08b99cbff0a566aa4b005febef1a3db3711b72e into the official elease?

**Comment by carlosbrando** [comment]
@argent-smith Thanks for remember!

**Comment by argent-smith** [comment]
@carlosbrando thanks a lot!
