### ISSUE TITLE
Renaming .autotest to .autotest.backup fails

### ISSUE THREAD

**Issue by nielsm** [carlosbrando/autotest-notification#2]
With the 2.2.0 version of the gem, you get this error if you already have a .autotest file and try to use an-install:

an-install:89: uninitialized constant FileUtils

There doesn't appear to be a require 'fileutils;, which if manually added eliminates the error message.

**Comment by carlosbrando** [comment]
nielsm, can you create a patch for this?

**Comment by carlosbrando** [comment]
Don't need anymore, I changed it.
